### ISSUE TITLE
[Question :❓] Info on https://apprepo.de/

### ISSUE THREAD

**Issue by nandgator** [AlexWoroschilow/Dictionary.AppImage#3]
![image](https://user-images.githubusercontent.com/38415384/116783416-442f9d00-aaac-11eb-9df0-71e12864ee65.png)

Sorry, I didn't find a better place to ask. Are you the maintainer of https://apprepo.de/ website. If so will the source code and CI builds be made public in the future soon? (cause it claims to be open source)

![image](https://user-images.githubusercontent.com/38415384/116783372-00d52e80-aaac-11eb-9589-ee246d0e0a39.png)

> In case you're complete unrelated, please ignore and close this issue.

**Comment by AlexWoroschilow** [comment]
Hi, yes, i am the maintainer. 
The source code is already open, you can check it here: https://github.com/area-of-dev 
My own CI server uses all these repositories  to rebuild the appimages every day and uploads it directly to the apprepo.

**Comment by nandgator** [comment]
Hi, thanks for the conformation. Are the CI workflow files opensource too?

**Comment by AlexWoroschilow** [comment]
I don`t see the CI workflow scripts anyhow important to make them open(close)sourced. They might be... except the application unique keys. They are necessary to upload the builds and they can not be publicly accessible.

**Comment by AlexWoroschilow** [comment]
The CI scripts only clone the repository, run `make` then upload the builds. If you have an idea how to make the builds publicly and then upload the builds safely, let me know. It wasn't my focus yet.

**Comment by nandgator** [comment]
I'm not an expert in this area but here's a [workflow file](https://github.com/srevinsaju/Firefox-Appimage/blob/master/.github/workflows/release.yml) which builds Firefox AppImages. Btw I like the AppRepo (sorry for being inquisitive but is the website code open-sourced?)

**Comment by AlexWoroschilow** [comment]
I looks like the github-actions workflow. I use jenkins instead of the github-actions. There are no such files as in your example. The website code is open as well: https://github.com/area-of-dev/Store-Web.AppImage Why are you asking?

**Comment by nandgator** [comment]
Thanks! I really like Appimages, even thought about creating something similar to AppRepo, but when I stumbled upon this website I wanted to improve it rather than creating a different one. I was making sure that it was legit and open source so that I can do tiny contributions from my limited yet growing knowledge.

**Comment by AlexWoroschilow** [comment]
I would appreciate any help. If you already have something in mind let me know. Or send a PR, i will take a look at it.
